-- MANZOR TECH full-stack platform schema
-- Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;
do $$ begin create type public.user_role as enum ('customer','employee','admin'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text not null default '', phone text not null default '',
 role public.user_role not null default 'customer',
 status text not null default 'active' check(status in('active','suspended')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.user_system_permissions (
 user_id uuid not null references public.profiles(id) on delete cascade,
 system_key text not null,
 can_access boolean not null default true,
 granted_by uuid references public.profiles(id), granted_at timestamptz not null default now(),
 primary key(user_id,system_key)
);
create table if not exists public.activity_log (
 id bigint generated by default as identity primary key,
 actor_id uuid references public.profiles(id), action text not null,
 target_type text,target_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name,phone,role)
 values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'phone',''),'customer')
 on conflict(id) do nothing;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_system_permissions enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "profile self read" on public.profiles;
create policy "profile self read" on public.profiles for select to authenticated using(id=auth.uid());
drop policy if exists "permissions self read" on public.user_system_permissions;
create policy "permissions self read" on public.user_system_permissions for select to authenticated using(user_id=auth.uid());

-- Administrative reads and writes are performed only by protected server API routes using the service role key.
