"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {getSession,insert,select,signOut} from "@/lib/supabase-rest";
type Ticket={id:string;ticket_number:number;subject:string;body:string;status:string;created_at:string};type Message={id:string;ticket_id:string;message:string;is_staff:boolean;created_at:string};
const statusLabel:Record<string,string>={open:"مفتوحة",in_progress:"قيد المعالجة",waiting_customer:"بانتظار ردك",resolved:"تم الحل",closed:"مغلقة"};const ticketCode=(n:number)=>`MT-${String(n||0).padStart(6,"0")}`;
export default function Profile(){const [p,setP]=useState<any>(null);const [tickets,setTickets]=useState<Ticket[]>([]);const [messages,setMessages]=useState<Message[]>([]);const [subject,setSubject]=useState("");const [body,setBody]=useState("");const [activeId,setActiveId]=useState<string|null>(null);const [reply,setReply]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const router=useRouter();
 async function load(){const s=getSession();if(!s)return router.replace("/login");const rows=await select<any[]>("profiles","select=*&id=eq."+s.user.id);const data=rows[0];if(data?.role!=="customer")return router.replace("/platform");setP(data);const [t,m]=await Promise.all([select<Ticket[]>("tickets",`select=*&customer_id=eq.${s.user.id}&order=created_at.desc`),select<Message[]>("ticket_messages","select=*&order=created_at.asc")]);setTickets(t);setMessages(m);if(!activeId&&t[0])setActiveId(t[0].id)}
 useEffect(()=>{load().catch(()=>router.replace("/login"))},[]);
 async function addTicket(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const s=getSession()!;const created=await insert<Ticket[]>("tickets",{customer_id:s.user.id,subject:subject.trim(),body:body.trim()});setSubject("");setBody("");if(created?.[0])setActiveId(created[0].id);await load()}catch(e:any){setError(e.message||"تعذر ارسال التذكرة")}finally{setBusy(false)}}
 async function replyToTicket(e:FormEvent){e.preventDefault();if(!activeId||!reply.trim())return;setBusy(true);try{const s=getSession()!;await insert("ticket_messages",{ticket_id:activeId,sender_id:s.user.id,message:reply.trim()});setReply("");await load()}catch(e:any){setError(e.message||"تعذر ارسال الرد")}finally{setBusy(false)}}
 function logout(){signOut();router.replace("/")}const active=tickets.find(t=>t.id===activeId)||null;const thread=useMemo(()=>messages.filter(m=>m.ticket_id===activeId),[messages,activeId]);if(!p)return <div className="loading">جاري تحميل الحساب</div>;
 return <main className="app-shell"><div className="topbar"><Link href="/">الموقع</Link><button className="action secondary" onClick={logout}>تسجيل الخروج</button></div><section className="panel"><h1>ملفي الشخصي</h1><div className="profile-grid"><div className="profile-item"><small>الاسم</small><strong>{p.full_name}</strong></div><div className="profile-item"><small>البريد</small><strong>{p.email}</strong></div><div className="profile-item"><small>نوع الحساب</small><strong>عميل</strong></div></div></section>
 <section className="panel"><h2>فتح تذكرة جديدة</h2>{error&&<div className="message error">{error}</div>}<form onSubmit={addTicket}><label className="field">عنوان التذكرة<input required value={subject} onChange={(e:any)=>setSubject(e.target.value)}/></label><label className="field">التفاصيل<textarea required rows={4} value={body} onChange={(e:any)=>setBody(e.target.value)}/></label><button className="action primary" disabled={busy}>{busy?"جاري الارسال":"ارسال التذكرة"}</button></form></section>
 <section className="panel ticket-customer-layout"><aside><h2>تذاكري</h2><div className="ticket-list">{tickets.map(t=><button className={`ticket ticket-select ${activeId===t.id?"active":""}`} key={t.id} onClick={()=>setActiveId(t.id)}><span className="ticket-code">{ticketCode(t.ticket_number)}</span><strong>{t.subject}</strong><small>{statusLabel[t.status]||t.status}</small></button>)}{!tickets.length&&<p>ما عندك تذاكر حاليا</p>}</div></aside><div className="ticket-detail">{active?<><div className="ticket-detail-head"><div><span className="ticket-code">{ticketCode(active.ticket_number)}</span><h2>{active.subject}</h2><small>{statusLabel[active.status]||active.status}</small></div></div><div className="conversation"><article className="bubble customer"><small>رسالتك</small><p>{active.body}</p></article>{thread.map(m=><article key={m.id} className={`bubble ${m.is_staff?"staff":"customer"}`}><small>{m.is_staff?"رد الدعم":"ردك"}</small><p>{m.message}</p><time>{new Date(m.created_at).toLocaleString("ar-SA")}</time></article>)}</div>{active.status!=="closed"&&<form className="reply-form" onSubmit={replyToTicket}><label className="field">اضافة رد<textarea required rows={3} value={reply} onChange={(e:any)=>setReply(e.target.value)}/></label><button className="action primary" disabled={busy}>ارسال الرد</button></form>}</>:<div className="empty-state">اختر تذكرة لعرض الردود</div>}</div></section></main>}
