import {
  Users,
  Receipt,
  Send,
  MailPlus,
  Inbox,
  UserRound,
  Settings,
  Monitor,
  ShieldCheck,
  Globe,
  MessageCircle,
  UsersRound,
  LifeBuoy,
} from 'lucide-react';

export const systems = [
  { titleAr: 'إدارة العملاء', titleEn: 'Customer Management', href: '/customers', icon: Users },
  { titleAr: 'المحاسبة', titleEn: 'Accounting', href: '/accounting', icon: Receipt },
  { titleAr: 'مرسل واتساب', titleEn: 'WhatsApp Sender', href: '/whatsapp-sender', icon: Send },
  { titleAr: 'مرسل البريد', titleEn: 'Email Sender', href: '/email-sender', icon: MailPlus },
  { titleAr: 'لوحة البريد', titleEn: 'Email Dashboard', href: '/email-dashboard', icon: Inbox },
  { titleAr: 'الموارد البشرية', titleEn: 'Human Resources', href: '/hr', icon: UserRound },
  { titleAr: 'الإعدادات', titleEn: 'Settings', href: '/settings', icon: Settings, adminOnly: true },
  { titleAr: 'متابعة المهام', titleEn: 'Task Monitor', href: '/monitor', icon: Monitor },
  { titleAr: 'منظور فولت', titleEn: 'Manzor Vault', href: '/vault', icon: ShieldCheck },
  { titleAr: 'الموقع الإلكتروني', titleEn: 'Website', href: '/website', icon: Globe },
  { titleAr: 'واتساب', titleEn: 'WhatsApp', href: '/whatsapp', icon: MessageCircle },
  { titleAr: 'منظور تيم', titleEn: 'Manzor Team', href: '/team', icon: UsersRound },
  { titleAr: 'تذاكر العملاء', titleEn: 'Customer Tickets', href: '/customer-tickets', icon: LifeBuoy },
];
