'use client';
import { useEffect, useMemo, useState } from 'react';
import { Search, Save } from 'lucide-react';
import { systems } from '../../lib/systems';
const labels={admin:'مدير',employee:'موظف',customer:'عميل'};
export default function UserManagement(){
 const [users,setUsers]=useState([]),[selectedId,setSelectedId]=useState(null),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 async function authHeaders(){const {data:{session}}=await (await import('../../lib/supabase/client')).createClient().auth.getSession();return {Authorization:`Bearer ${session?.access_token||''}`,'content-type':'application/json'}}
 async function load(){setLoading(true); const r=await fetch('/api/admin/users',{cache:'no-store',headers:await authHeaders()}); const j=await r.json(); if(r.ok){setUsers(j.users); setSelectedId(x=>x||j.users?.[0]?.id)} else setMsg(j.error); setLoading(false)}
 useEffect(()=>{load()},[]);
 const selected=users.find(u=>u.id===selectedId); const filtered=useMemo(()=>users.filter(u=>(`${u.full_name} ${u.email}`).toLowerCase().includes(q.toLowerCase())),[users,q]);
 function patch(changes){setUsers(us=>us.map(u=>u.id===selectedId?{...u,...changes}:u))}
 async function save(){setSaving(true);setMsg(''); const r=await fetch('/api/admin/users',{method:'PATCH',headers:await authHeaders(),body:JSON.stringify(selected)}); const j=await r.json(); setMsg(r.ok?'تم حفظ الصلاحيات':j.error); setSaving(false)}
 if(loading) return <section className="card">جاري تحميل المستخدمين...</section>;
 return <div className="user-management-grid"><section className="card users-panel"><label className="search-field"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم او البريد"/></label><div className="users-list">{filtered.map(u=><button key={u.id} className={u.id===selectedId?'user-row active':'user-row'} onClick={()=>setSelectedId(u.id)}><span className="avatar">{(u.full_name||u.email||'?')[0]}</span><span className="user-main"><strong>{u.full_name||'بدون اسم'}</strong><small>{u.email}</small></span><span className="role-badge">{labels[u.role]}</span></button>)}</div></section>
 {selected&&<section className="card access-panel"><div className="profile-head"><span className="avatar large">{(selected.full_name||selected.email)[0]}</span><div><h3>{selected.full_name||'بدون اسم'}</h3><p>{selected.email}</p></div></div><div className="settings-form-grid"><label>نوع الحساب<select value={selected.role} onChange={e=>patch({role:e.target.value})}><option value="customer">عميل — Customer</option><option value="employee">موظف — Employee</option><option value="admin">مدير — Admin</option></select></label><label>حالة الحساب<select value={selected.status} onChange={e=>patch({status:e.target.value})}><option value="active">نشط</option><option value="suspended">موقوف</option></select></label></div><div className="permissions-head"><div><h3>صلاحيات الانظمة</h3><p>الايقونات التي تظهر لهذا المستخدم</p></div><span>{selected.apps.length} نظام</span></div><div className="permissions-grid">{systems.filter(s=>!s.adminOnly).map(s=>{const I=s.icon,en=selected.apps.includes(s.key);return <button key={s.key} className={en?'permission-card enabled':'permission-card'} onClick={()=>patch({apps:en?selected.apps.filter(x=>x!==s.key):[...selected.apps,s.key]})}><span className="permission-icon"><I size={20}/></span><span><strong>{s.titleAr}</strong><small>{s.titleEn}</small></span><span className={en?'switch on':'switch'}><i/></span></button>})}</div>{msg&&<div className="auth-message">{msg}</div>}<div className="settings-actions"><button disabled={saving} onClick={save} className="btn primary"><Save size={18}/>{saving?'جاري الحفظ':'حفظ التغييرات'}</button></div></section>}</div>
}
